# Use root/example as user/password credentials
version: "3.8"

services:
  app:
    container_name: cms
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development #指定构建阶段
      args:
        - APP_ENV
    command: pnpm start:dev
    env_file:
      - .env.development
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3000:3000
